// Reimplements the add-on's file generators (resources/lib/kodi/installer.py:
// build_playercorefactory_file_xml + build_keymap_file_xml) in the configurator, per
// CONFIGURATOR_HANDOFF.md decision A. The configurator runs on Windows and cannot import the
// add-on's Kodi-bound Python, so the deterministic template output is reproduced here. Keep
// in sync with installer.py if the add-on's templates change.

export type KodiPlatform = "coreelec" | "android" | "windows" | "linux";

export type KodiTarget = {
  pythonPath: string;
  /** Absolute path to resources/lib/external_player.py on the Kodi box. */
  externalPlayerScript: string;
  /** Absolute path to userdata/addon_data/<id> on the Kodi box. */
  addonDataDir: string;
};

const ADDON_ID = "script.oppo203.iso.external";

// Mirror of resources/lib/oppo/constants.py XML_4K_TAG_FILENAME_PATTERN.
const XML_4K_TAG_FILENAME_PATTERN = ".*(4K|4k|UHD|uhd|2160p|2160P).*";

const PATHS_BY_PLATFORM: Record<KodiPlatform, { addons: string; userdata: string; sep: string }> = {
  coreelec: { addons: "/storage/.kodi/addons", userdata: "/storage/.kodi/userdata", sep: "/" },
  android: {
    addons: "/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons",
    userdata: "/sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata",
    sep: "/",
  },
  windows: { addons: "%APPDATA%\\Kodi\\addons", userdata: "%APPDATA%\\Kodi\\userdata", sep: "\\" },
  linux: { addons: "~/.kodi/addons", userdata: "~/.kodi/userdata", sep: "/" },
};

const DEFAULT_PYTHON_BY_PLATFORM: Record<KodiPlatform, string> = {
  coreelec: "/usr/bin/python3",
  android: "/usr/bin/python3",
  windows: "python",
  linux: "/usr/bin/python3",
};

/** Standard Kodi-box paths for a platform; pythonPath overrides the platform default. */
export function kodiTargetForPlatform(platform: KodiPlatform, pythonPath?: string): KodiTarget {
  const { addons, userdata, sep } = PATHS_BY_PLATFORM[platform];
  return {
    pythonPath: pythonPath && pythonPath.trim() !== "" ? pythonPath : DEFAULT_PYTHON_BY_PLATFORM[platform],
    externalPlayerScript: [addons, ADDON_ID, "resources", "lib", "external_player.py"].join(sep),
    addonDataDir: [userdata, "addon_data", ADDON_ID].join(sep),
  };
}

/** The Kodi userdata directory for a platform (where playercorefactory.xml + keymaps/ live). */
export function userdataDirForPlatform(platform: KodiPlatform): string {
  return PATHS_BY_PLATFORM[platform].userdata;
}

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function indent(text: string, prefix: string): string {
  return text
    .split("\n")
    .map((line) => (line ? prefix + line : line))
    .join("\n");
}

export function buildPlayerElementXml(target: KodiTarget): string {
  const python = xmlEscape(target.pythonPath);
  const script = xmlEscape(target.externalPlayerScript);
  const data = xmlEscape(target.addonDataDir);
  return `<player name="Oppo203ISO" type="ExternalPlayer" audio="false" video="true">
      <filename>${python}</filename>
      <args>"${script}" --addon-data "${data}" --file "{1}"</args>
      <hidexbmc>false</hidexbmc>
      <hideconsole>true</hideconsole>
      <warpcursor>none</warpcursor>
      <playcountminimumtime>1</playcountminimumtime>
</player>`;
}

export function buildRuleXml(includeDiscFolderRules: boolean): string {
  const lines = [
    "<!-- Conservative 4K/UHD/2160p tag-aware routing. XML mode is filename/path driven; -->",
    "<!-- it cannot inspect metadata, NFO files, stream resolution, or ISO internals. -->",
    `<rule filetypes="iso" filename="${XML_4K_TAG_FILENAME_PATTERN}" player="Oppo203ISO"/>`,
  ];
  if (includeDiscFolderRules) {
    lines.push(
      "",
      "<!-- Tagged BDMV and playlist entry files. -->",
      `<rule filetypes="bdmv" filename="${XML_4K_TAG_FILENAME_PATTERN}" player="Oppo203ISO"/>`,
      `<rule filetypes="mpls" filename="${XML_4K_TAG_FILENAME_PATTERN}" player="Oppo203ISO"/>`,
    );
  }
  return lines.join("\n");
}

export function buildPlayercorefactoryXml(target: KodiTarget, includeDiscFolderRules = true): string {
  const header = `<!--
  playercorefactory.xml generated by the OppoKodiAddon Configurator.
  Ready to use: copy this file into your Kodi userdata folder (next to
  advancedsettings.xml), then restart Kodi. If you already have a
  playercorefactory.xml, merge the <player> and <rule> entries instead.
-->`;
  return (
    header +
    "\n<playercorefactory>\n  <players>\n" +
    indent(buildPlayerElementXml(target), "    ") +
    "\n  </players>\n" +
    '  <rules action="prepend">\n' +
    indent(buildRuleXml(includeDiscFolderRules), "    ") +
    "\n  </rules>\n" +
    "</playercorefactory>\n"
  );
}

export const KEYMAP_FILENAME = "oppo203iso.xml";

const KEYMAP_DOCUMENT = `<keymap>
  <FullscreenVideo>
    <keyboard>
      <up>RunScript(${ADDON_ID},oppo_key,up)</up>
      <down>RunScript(${ADDON_ID},oppo_key,down)</down>
      <left>RunScript(${ADDON_ID},oppo_key,left)</left>
      <right>RunScript(${ADDON_ID},oppo_key,right)</right>
      <enter>RunScript(${ADDON_ID},oppo_key,select)</enter>
      <return>RunScript(${ADDON_ID},oppo_key,back)</return>
      <m>RunScript(${ADDON_ID},oppo_key,popup_menu)</m>
      <t>RunScript(${ADDON_ID},oppo_key,top_menu)</t>
      <space>RunScript(${ADDON_ID},oppo_key,play)</space>
      <p>RunScript(${ADDON_ID},oppo_key,play)</p>
      <f>RunScript(${ADDON_ID},oppo_key,forward)</f>
      <r>RunScript(${ADDON_ID},oppo_key,reverse)</r>
      <x>RunScript(${ADDON_ID},oppo_key,stop)</x>
      <a>RunScript(${ADDON_ID},oppo_key,cycle_audio)</a>
      <l>RunScript(${ADDON_ID},oppo_key,cycle_subtitle)</l>
      <volume_up>RunScript(${ADDON_ID},oppo_key,volume_up)</volume_up>
      <volume_down>RunScript(${ADDON_ID},oppo_key,volume_down)</volume_down>
      <volume_mute>RunScript(${ADDON_ID},oppo_key,mute)</volume_mute>
      <o>RunScript(${ADDON_ID},oppo_key,option)</o>
      <i>RunScript(${ADDON_ID},oppo_key,info)</i>
      <pageup>RunScript(${ADDON_ID},oppo_key,page_up)</pageup>
      <pagedown>RunScript(${ADDON_ID},oppo_key,page_down)</pagedown>
      <F1>RunScript(${ADDON_ID},oppo_key,red)</F1>
      <F2>RunScript(${ADDON_ID},oppo_key,green)</F2>
      <F3>RunScript(${ADDON_ID},oppo_key,blue)</F3>
      <F4>RunScript(${ADDON_ID},oppo_key,yellow)</F4>
      <home>RunScript(${ADDON_ID},oppo_key,seek_beginning)</home>
    </keyboard>
    <remote>
      <up>RunScript(${ADDON_ID},oppo_key,up)</up>
      <down>RunScript(${ADDON_ID},oppo_key,down)</down>
      <left>RunScript(${ADDON_ID},oppo_key,left)</left>
      <right>RunScript(${ADDON_ID},oppo_key,right)</right>
      <select>RunScript(${ADDON_ID},oppo_key,select)</select>
      <back>RunScript(${ADDON_ID},oppo_key,back)</back>
      <menu>RunScript(${ADDON_ID},oppo_key,popup_menu)</menu>
      <title>RunScript(${ADDON_ID},oppo_key,top_menu)</title>
      <play>RunScript(${ADDON_ID},oppo_key,play)</play>
      <pause>RunScript(${ADDON_ID},oppo_key,pause)</pause>
      <stop>RunScript(${ADDON_ID},oppo_key,stop)</stop>
      <forward>RunScript(${ADDON_ID},oppo_key,forward)</forward>
      <reverse>RunScript(${ADDON_ID},oppo_key,reverse)</reverse>
      <skipplus>RunScript(${ADDON_ID},oppo_key,skip_next)</skipplus>
      <skipminus>RunScript(${ADDON_ID},oppo_key,skip_previous)</skipminus>
      <audio>RunScript(${ADDON_ID},oppo_key,cycle_audio)</audio>
      <subtitle>RunScript(${ADDON_ID},oppo_key,cycle_subtitle)</subtitle>
      <volumeplus>RunScript(${ADDON_ID},oppo_key,volume_up)</volumeplus>
      <volumeminus>RunScript(${ADDON_ID},oppo_key,volume_down)</volumeminus>
      <mute>RunScript(${ADDON_ID},oppo_key,mute)</mute>
      <red>RunScript(${ADDON_ID},oppo_key,red)</red>
      <green>RunScript(${ADDON_ID},oppo_key,green)</green>
      <blue>RunScript(${ADDON_ID},oppo_key,blue)</blue>
      <yellow>RunScript(${ADDON_ID},oppo_key,yellow)</yellow>
      <info>RunScript(${ADDON_ID},oppo_key,info)</info>
      <pageplus>RunScript(${ADDON_ID},oppo_key,page_up)</pageplus>
      <pageminus>RunScript(${ADDON_ID},oppo_key,page_down)</pageminus>
    </remote>
  </FullscreenVideo>
</keymap>`;

export function buildKeymapXml(): string {
  return `<!--
  Oppo UDP-203 remote-bridge keymap, generated by the OppoKodiAddon Configurator.
  Copy this file into your Kodi userdata/keymaps folder, then restart Kodi
  (or run the built-in ReloadKeymaps action).
-->
${KEYMAP_DOCUMENT}
`;
}

/** The two generated files keyed by their path relative to Kodi userdata/. */
export function buildTransferFiles(
  target: KodiTarget,
  includeDiscFolderRules = true,
): Record<string, string> {
  return {
    "playercorefactory.xml": buildPlayercorefactoryXml(target, includeDiscFolderRules),
    [`keymaps/${KEYMAP_FILENAME}`]: buildKeymapXml(),
  };
}
