#!/usr/bin/env python3
"""Build 16 i18n extraction facade for Kodi gettext templates.

This tool is the transition point away from calling ``tools/make_pot.py``
directly.  The add-on uses Kodi numeric localization ids stored as gettext
``msgctxt`` values (for example ``#31000``), so the legacy extractor remains
available as a deterministic fallback while a Babel/gettext-style workflow is
introduced.

The Build 16 policy is intentionally dependency-safe:

* ``--backend auto`` never requires Babel to be installed.
* ``--backend legacy`` explicitly exercises the preserved ``make_pot.py`` path.
* ``--backend babel`` requires the Babel Python package to be importable, but
  still renders through the Kodi-id template renderer so numeric msgctxt ids are
  preserved exactly.
* ``--check`` performs a dry-run and verifies that the facade and legacy
  extractor agree, without writing ``resources/language/strings.pot``.
"""
from __future__ import annotations

import argparse
import importlib.util
import os
from pathlib import Path
import sys
from typing import Iterable

DEFAULT_OUTPUT = "resources/language/strings.pot"
SUPPORTED_BACKENDS = ("auto", "legacy", "babel")
LEGACY_EXTRACTOR = "tools/make_pot.py"
PRIMARY_EXTRACTOR = "tools/i18n_extract.py"
LEGACY_ALIAS_STATUS = "retained_legacy_compatibility_alias"


def legacy_alias_policy() -> dict[str, str]:
    """Return Build 16 policy for the preserved legacy extractor.

    Build 16 makes the retirement decision explicit: ``tools/make_pot.py`` is
    retained as a documented compatibility alias and deterministic parser, but
    callers should migrate to this facade for new automation.
    """
    return {
        "primary": PRIMARY_EXTRACTOR,
        "legacy_alias": LEGACY_EXTRACTOR,
        "status": LEGACY_ALIAS_STATUS,
        "removal_policy": "not removed in Build 16",
    }


def project_root(start: Path | None = None) -> Path:
    start = (start or Path.cwd()).resolve()
    for candidate in (start, *start.parents):
        if (candidate / "addon.xml").exists() and (candidate / "resources" / "settings.xml").exists():
            return candidate
    raise RuntimeError("Could not find add-on root containing addon.xml and resources/settings.xml")


def _load_make_pot(root: Path):
    path = root / "tools" / "make_pot.py"
    spec = importlib.util.spec_from_file_location("make_pot_build16_fallback", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load legacy extractor from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def babel_available() -> bool:
    """Return True when the optional Babel package is importable."""
    return importlib.util.find_spec("babel") is not None


def select_backend(requested: str) -> str:
    """Resolve the requested backend to the backend used for this run."""
    if requested not in SUPPORTED_BACKENDS:
        raise ValueError(f"unsupported backend: {requested}")
    if requested == "legacy":
        return "legacy"
    if requested == "babel":
        if not babel_available():
            raise RuntimeError("Babel backend requested but the Babel package is not installed")
        return "babel"
    return "babel" if babel_available() else "legacy"


def collect_ids(root: Path) -> set[int]:
    """Collect Kodi localization ids using the preserved deterministic parser."""
    make_pot = _load_make_pot(root)
    return set(make_pot.collect_ids(str(root)))


def render_template(ids: Iterable[int], *, generator: str = "tools/i18n_extract.py") -> str:
    """Render a Kodi-compatible gettext template for numeric msgctxt ids."""
    lines = [
        "# Kodi .pot template for Oppo UDP-203 ISO External Player",
        f"# Auto-generated by {generator} - do not edit by hand.",
        "# Build 16 treats tools/make_pot.py as the legacy compatibility alias and fallback extractor.",
        "",
    ]
    for number in sorted(set(ids)):
        lines.append(f'msgctxt "#{number}"')
        lines.append('msgid ""')
        lines.append('msgstr ""')
        lines.append("")
    return "\n".join(lines)


def render_legacy_template(root: Path) -> str:
    """Render through tools/make_pot.py exactly for fallback comparison."""
    make_pot = _load_make_pot(root)
    return str(make_pot.render_pot(make_pot.collect_ids(str(root))))


def render_facade_template(root: Path, backend: str) -> tuple[str, str, int]:
    """Return rendered template, resolved backend name, and id count."""
    resolved = select_backend(backend)
    ids = collect_ids(root)
    # Babel support remains transition-safe in Build 16: when Babel is importable,
    # the facade may run in Babel mode, but the Kodi numeric-context renderer is
    # still used so L(31000) and L("#31000") output stays identical.
    return render_template(ids), resolved, len(ids)


def check_extraction(root: Path, backend: str) -> tuple[bool, str]:
    """Verify extraction can run and agrees with the preserved fallback ids."""
    rendered, resolved, count = render_facade_template(root, backend)
    legacy_ids = collect_ids(root)
    facade_ids = []
    for line in rendered.splitlines():
        if line.startswith('msgctxt "#') and line.endswith('"'):
            facade_ids.append(int(line.removeprefix('msgctxt "#').removesuffix('"')))
    if set(facade_ids) != legacy_ids:
        return False, f"backend={resolved}; facade ids differ from legacy fallback"
    if count == 0:
        return True, f"backend={resolved}; 0 ids; make_pot fallback preserved; legacy alias retained; no inline localization calls found"
    return True, f"backend={resolved}; {count} ids; make_pot fallback preserved; legacy alias retained"


def write_template(root: Path, out: str, backend: str) -> tuple[Path, str, int]:
    rendered, resolved, count = render_facade_template(root, backend)
    out_path = Path(out)
    if not out_path.is_absolute():
        out_path = root / out_path
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    return out_path, resolved, count


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Extract Kodi gettext template with Babel-safe fallback")
    parser.add_argument("--root", default=".", help="add-on root to scan")
    parser.add_argument("--out", default=DEFAULT_OUTPUT, help="output .pot path")
    parser.add_argument("--backend", choices=SUPPORTED_BACKENDS, default="auto", help="extractor backend")
    parser.add_argument("--check", action="store_true", help="dry-run validation without writing the .pot file")
    args = parser.parse_args(argv)

    root = project_root(Path(args.root))
    if args.check:
        ok, detail = check_extraction(root, args.backend)
        print(("OK" if ok else "FAIL") + f": i18n_extract - {detail}")
        return 0 if ok else 1

    try:
        out_path, resolved, count = write_template(root, args.out, args.backend)
    except Exception as exc:
        print(f"FAIL: i18n_extract - {exc}", file=sys.stderr)
        return 1
    print(f"wrote {out_path} ({count} ids; backend={resolved})")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
