#!/usr/bin/env python3
"""tools/make_pot.py - legacy compatibility alias for Kodi .pot extraction.

Build 16 keeps this script for callers that still invoke the historical
command directly. New automation should prefer ``tools/i18n_extract.py``,
which wraps this deterministic parser behind the i18n extraction facade.

Historical behavior: extract L(31xxx) calls into a .pot template.

Walks the addon source tree, collects every numeric id passed to
`L(...)` (or its aliases `_(...)`, `getLocalizedString(...)`,
`addon.getLocalizedString(...)`), and emits a Kodi-style .po template
(`resources/language/strings.pot`) listing every distinct id with an
empty msgid/msgstr ready for translators.

The output is deterministic (sorted by numeric id) so re-running on
unchanged source produces a byte-identical .pot file - making the
template safe to commit.

Usage:
    python tools/make_pot.py [--root <path>] [--out <pot path>]

The script has zero third-party dependencies; it tokenises with the
stdlib `tokenize` module so it works on any Python installation.
"""

from __future__ import annotations

import argparse
import io
import os
import re
import sys
import tokenize
from collections.abc import Iterable

# Function names that introduce a localised string id.  L() is the
# addon's primary helper; _() is the gettext convention; the two
# Kodi-native names are also matched in case they are used directly.
_FUNC_NAMES = {"L", "_", "getLocalizedString"}

# Match #3xxxx ids whether they appear as 31000 or "#31000".
_ID_RE = re.compile(r"^#?(\d{5})$")

LEGACY_ALIAS_FOR = "tools/i18n_extract.py"
LEGACY_ALIAS_STATUS = "retained_legacy_compatibility_alias"


def legacy_alias_notice() -> str:
    """Return the Build 16 compatibility notice for this legacy entrypoint."""
    return "tools/make_pot.py is retained as a legacy compatibility alias; use tools/i18n_extract.py for new automation."


# Vendored / generated / VCS / cache trees that never contain add-on
# localization ids.  Skipping them keeps extraction fast and deterministic
# regardless of a local virtualenv (.venv often holds 1000s of .py files) or
# build output.
_SKIP_DIRS = frozenset(
    (
        "__pycache__",
        ".git",
        "tests",
        "tools",
        "output",
        ".venv",
        "venv",
        "env",
        ".tox",
        "build",
        "dist",
        "node_modules",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
    )
)


def _iter_python_files(root: str) -> Iterable[str]:
    for dirpath, dirnames, filenames in os.walk(root):
        # Prune vendored / generated trees in place so os.walk does not
        # descend into them.
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS]
        for fn in filenames:
            if fn.endswith(".py"):
                yield os.path.join(dirpath, fn)


def _ids_in_source(text: str) -> set[int]:
    """Return the set of #3xxxx ids referenced via L(), _(), etc."""
    ids: set[int] = set()
    try:
        tokens = list(tokenize.generate_tokens(io.StringIO(text).readline))
    except tokenize.TokenError:
        return ids
    for i, tok in enumerate(tokens):
        if tok.type != tokenize.NAME or tok.string not in _FUNC_NAMES:
            continue
        # Need next token to be `(` and the one after to be a NUMBER
        # or STRING that parses to a #3xxxx id.
        if i + 2 >= len(tokens):
            continue
        nxt = tokens[i + 1]
        arg = tokens[i + 2]
        if nxt.type != tokenize.OP or nxt.string != "(":
            continue
        if arg.type == tokenize.NUMBER:
            m = _ID_RE.match(arg.string)
        elif arg.type == tokenize.STRING:
            # Strip quotes
            s = arg.string.strip()
            if (s.startswith('"') and s.endswith('"')) or (s.startswith("'") and s.endswith("'")):
                s = s[1:-1]
            m = _ID_RE.match(s)
        else:
            m = None
        if m:
            n = int(m.group(1))
            if 30000 <= n <= 32999:
                ids.add(n)
    return ids


def collect_ids(root: str) -> set[int]:
    """Walk `root` and collect every referenced id."""
    out: set[int] = set()
    for p in _iter_python_files(root):
        try:
            with open(p, "r", encoding="utf-8") as f:
                out.update(_ids_in_source(f.read()))
        except OSError:
            continue
    return out


def render_pot(ids: Iterable[int]) -> str:
    """Render the .pot template - one entry per id, sorted ascending."""
    lines = [
        "# Kodi .pot template for Oppo UDP-203 ISO External Player",
        "# Auto-generated by tools/make_pot.py - do not edit by hand.",
        "",
    ]
    for n in sorted(set(ids)):
        lines.append('msgctxt "#' + str(n) + '"')
        lines.append('msgid ""')
        lines.append('msgstr ""')
        lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--root", default=".", help="addon root to scan (default: cwd)")
    p.add_argument("--out", default="resources/language/strings.pot", help="output .pot path")
    args = p.parse_args(argv)
    ids = collect_ids(args.root)
    pot = render_pot(ids)
    out_path = os.path.join(args.root, args.out) if not os.path.isabs(args.out) else args.out
    d = os.path.dirname(out_path)
    if d:
        os.makedirs(d, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(pot)
    print("wrote", out_path, "(" + str(len(ids)) + " ids)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
