"""v2.9.1 Build 16 - Babel/gettext extraction transition tests."""

from __future__ import annotations

import importlib.util
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _load_i18n_extract():
    spec = importlib.util.spec_from_file_location(
        "i18n_extract_build16", ROOT / "tools" / "i18n_extract.py"
    )
    tool = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(tool)
    return tool


def _load_make_pot():
    spec = importlib.util.spec_from_file_location(
        "make_pot_build16", ROOT / "tools" / "make_pot.py"
    )
    tool = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(tool)
    return tool


def _load_package_tool():
    spec = importlib.util.spec_from_file_location(
        "package_installable_zip_build16", ROOT / "tools" / "package_installable_zip.py"
    )
    tool = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(tool)
    return tool


def _load_audit():
    spec = importlib.util.spec_from_file_location(
        "audit_release_build16", ROOT / "tools" / "audit_release.py"
    )
    audit = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(audit)
    return audit


def test_i18n_extract_preserves_make_pot_fallback_contract():
    tool = _load_i18n_extract()
    make_pot = _load_make_pot()
    assert tool.collect_ids(ROOT) == make_pot.collect_ids(str(ROOT))
    ok, detail = tool.check_extraction(ROOT, "legacy")
    assert ok is True
    assert "make_pot fallback preserved" in detail
    assert "legacy alias retained" in detail
    assert tool.select_backend("legacy") == "legacy"


def test_i18n_extract_renders_kodi_msgctxt_template_without_babel_dependency():
    tool = _load_i18n_extract()
    rendered = tool.render_template({31002, 31000}, generator="unit-test")
    assert "# Kodi .pot template" in rendered
    assert "Auto-generated by unit-test" in rendered
    assert 'msgctxt "#31000"' in rendered
    assert rendered.index('msgctxt "#31000"') < rendered.index('msgctxt "#31002"')
    assert "tools/make_pot.py as the legacy compatibility alias and fallback extractor" in rendered


def test_i18n_extract_cli_check_is_non_writing_and_safe():
    before = (ROOT / "resources" / "language" / "strings.pot").exists()
    result = subprocess.run(
        [sys.executable, str(ROOT / "tools" / "i18n_extract.py"), "--root", str(ROOT), "--check"],
        check=False,
        text=True,
        capture_output=True,
    )
    after = (ROOT / "resources" / "language" / "strings.pot").exists()
    assert result.returncode == 0, result.stdout + result.stderr
    assert "OK: i18n_extract" in result.stdout
    assert "make_pot fallback preserved" in result.stdout
    assert "legacy alias retained" in result.stdout
    assert after == before


def test_babel_cfg_and_verify_script_wire_build16_extraction_transition():
    cfg = (ROOT / "babel.cfg").read_text(encoding="utf-8")
    verify = (ROOT / "scripts" / "verify.sh").read_text(encoding="utf-8")
    assert "Build 16 transitional Babel/gettext extraction configuration" in cfg
    assert "keywords = L:1" in cfg
    assert "getLocalizedString:1" in cfg
    assert 'python3 tools/i18n_extract.py --root "$ROOT" --check' in verify
    assert "tools/make_pot.py" in verify


def test_runtime_zip_excludes_build16_i18n_development_tooling(tmp_path):
    package_tool = _load_package_tool()
    assert package_tool.is_runtime_member("tools/i18n_extract.py") is False
    assert package_tool.is_runtime_member("tools/make_pot.py") is False
    assert package_tool.is_runtime_member("babel.cfg") is False
    out = tmp_path / "runtime.zip"
    names = package_tool.create_installable_zip(ROOT, out)
    assert all("tools/i18n_extract.py" not in name for name in names)
    with zipfile.ZipFile(out) as zf:
        packaged = set(zf.namelist())
    assert "script.oppo203.iso.external/babel.cfg" not in packaged


def test_release_audit_requires_build16_manifest_and_i18n_evidence():
    audit = _load_audit()
    results = audit.run_audit(ROOT, expected_version="2.9.13")
    failed = [item for item in results if item["status"] != "ok"]
    assert failed == []
    names = {item["name"] for item in results}
    assert "file:release-evidence/v2.9.1-build16/MANIFEST.txt" in names
    assert "file:tools/i18n_extract.py" in names
    assert "file:tools/make_pot.py" in names
    assert "file:babel.cfg" in names
    assert "file:BUILD_NOTES_v2.9.1_BUILD16.md" in names
    assert "file:TEST_AUDIT_REPORT_v2.9.1_BUILD16.md" in names


def test_addon_metadata_and_version_source_identify_build16():
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from resources.lib import version

    addon_text = (ROOT / "addon.xml").read_text(encoding="utf-8")
    assert version.BUILD_ID == "v2.9.13 Final"
    assert version.BUILD_NUMBER == 22
    assert "Version 2.9.10 Build 2" in addon_text
    assert "Babel/gettext extraction" in addon_text
    assert "tools/make_pot.py as a legacy compatibility alias" in addon_text
